/* Copyright (C) 2013,Market Ruler,LLC. All Rights Reserved. Updated: 2013-10-30 16:40:46 */var dD=document;var CRUser='6f6c9d9c3b082208260ab20bf57f5c18';var CRCrossCode='';var CRLandingCode='';var CRLandTime='1384290841';var CRMemory='';var __CR={d: document,site: '6096' || window.siteid,frame: 0 },okay=true,valid=true,crcookie=CRUser,CRActionMinutes=15,CRScript=false,CRNoLand='',_cRd=(dD.URL.indexOf('crtest=1') >=0),_cRY=false,_cRT=false,_cRS=false,_cRI={},_cRaa=(dD.URL.indexOf('https') >=0) ? 's' : '',_ud='undefined';try{if(typeof top.document.URL !==_ud){__CR.frame=1;}}catch (e){}if(!_cRd && __CR.frame){_cRd=(top.document.URL.indexOf('crtest=1') >=0);}
function _cR0(){var n=new Date(),s="";return (s+Math.random()).substring(2,12)+n.getTime()+n.getMilliseconds();}
function _cRad(n){if(!dD.getElementsByTagName || !dD.createElement){return null;}var h=dD.getElementsByTagName(n);if(h.length > 0){return h[0];}var e=dD.createElement(n);dD.appendChild(e);return e;}var _c0=_cRad('head');var _c4=_cRad('body');var _c3=_cR0();function _c2(u){var n=_c3;var t;if(_c0){t='s';var x=dD.createElement("SCRIPT");x.type="text/javascript";x.charset="utf-8";x.async=x.defer=false;x.src=u+"&isjs=1&_r="+n;x.onload=function (){if(_cRd){alert('s:'+x.src);}};_c0.appendChild(x);}else{t='i';_cRI[n]=new Image();_cRI[n].onload=function (){if(_cRd){alert('i:'+u);}};_cRI[n].src=u+"&_r="+n;}if(_cRd){alert('ConversionRuler: Recording '+t+' '+u);}}
function _cRf(n,d){var c=dD.cookie;var s=c.indexOf(n+'=');if(s < 0){return d;}s+=n.length+1;var e=c.indexOf(';',s);if(e < 0){e=c.length;}return unescape(c.substring(s,e));}
function CR_QS(n){var p,i,d=arguments.length > 1 ? arguments[1] : null;var q=location.search;if(q.substring(0,1)==="?"){q=q.substring(1);}q=q.split("&");n=n.toLowerCase();for (i=0;i < q.length;i++){p=q[i].split("=",2);if(p.length===2 && p[0].toLowerCase()===n){ return unescape(p[1]);}}return d;}
function _cRt(n,v){var d=new Date();if(CRActionMinutes < 0){d.setFullYear(2020);}else if(CRActionMinutes > 0){var dd=parseInt(CRActionMinutes * 60000,10);d.setTime(d.getTime()+dd);}dD.cookie=n+"="+escape(v)+';path=/;expires='+d.toGMTString();return v;}
function CR_Cookie(n,v){return v ? _cRt(n,v) : _cRf(n,null);}
function _cRb(){}
function _cRa(){var t=__CR.site+'mem';var u="http"+_cRaa+"://www.conversionruler.com/bin/tracker.php?siteid="+__CR.site+"&cr_no=1&cr_m="+escape(CRMemory);_cRI[t]=new Image();_cRI[t].onload=_cRb;_cRI[t].src=u;_cRS=false;}
function _cRr(x,def){x+='';return (x===_ud || x==='null') ? def : x;}
function _cRy(x,def){if(_cRr(x,null)===null){return def;}var r=new RegExp('[^0-9.]','g');x+="";x=x.replace(r,'');return (x !=='') ? x : def;}
function _cRl(x,f,d){var i=x.indexOf(f);return (i >=0) ? x.substring(0,i) : d;}
function _cRq(x,f,d){var i=x.indexOf(f);return (i >=0) ? x.substring(i+f.length) : d;}
function _cRp(n,v){v=_cRr(v,"");return (v==="") ? "" : "&"+n+"="+escape(v);}
function _cRc(uds,v,s0,s1){var r=true;if(_cRd && !CRScript){v='js-not-called';r=false;}else if(v===''){if(uds===''){ return false;}v=uds;r=false;}dD.write(s0+v+s1);return r;}
function _cRm(n,a,f,v){var uds=(a.length > f) ? a[f++] : '';return _cRc(uds,v,'<input type="hidden" name="'+n+'" value="','" />');}
function _cRn(a,f,v){var s0=(a.length > f) ? a[f++] : '';var s1=(a.length > f) ? a[f++] : '';var uds=(a.length > f) ? a[f++] : '';return _cRc(uds,v,s0,s1);}
function _cRh(){var _s=screen;if(_s && _s.width && _s.height){var x=_s.width+"x"+_s.height;if(_s.colorDepth){ return x+"-"+_s.colorDepth;}if(_s.pixelDepth){ return x+"-"+_s.pixelDepth;}return x;}return "";}
function _cRj(){var n=navigator;return (n && n.javaEnabled()) ? '1' : '0';}
function _cRi(d){var k="0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz";return k.charAt(d.getFullYear() - 2000)+k.charAt(d.getMonth()+1)+k.charAt(d.getDate())+k.charAt(d.getHours())+k.charAt(d.getMinutes())+k.charAt(d.getSeconds());}
function _cRk(){var now=new Date();var qs=_cRp("ct",_cRi(now));if(now.getTimezoneOffset){qs=qs+_cRp("gmto",now.getTimezoneOffset());}return qs;}
function _cRs(){var r=window.document.referrer;if(__CR.frame){var u=_cRp("refb",top.document.referrer);if(dD.URL===top.document.URL){ return u;}return u+_cRp("tu",top.document.URL);}else{return _cRp("refb",r);}}
function _cRw(x,i,c){if(x.length < i+1){return x;}return x.substr(0,i)+c+x.substr(i+1,x.length-i-1);}
function _cRv(x){var i,j0,j1,c0,c1,r,c="0123456789ABCDEF";x+='';r="13579BDFECA86420";for (i=0;i < x.length;i++){j0=i&15;j1=(i+1)&15;c0=(x.charCodeAt(i) >> 4)&15;c1=(x.charCodeAt(i))&15;r=_cRw(r,j0,c.charAt(((c.indexOf(r.charAt(j0)) ^ c0)+x.length+i+19) & 15));r=_cRw(r,j1,c.charAt(((c.indexOf(r.charAt(j1)) ^ c1)+x.length+i+39) & 15));}return r;}
function _cRu(siteid,a,a0r,a0d,a1r,a1d,a2r,a2d,a3r,a3d){var cn="CR_"+siteid+"_"+a;var w=window;var n,i,aul='',aulv=['category','source','campaign','keyword','split','amount','text','landing_custom','cookie'];for (i=0;i < 8;i++){aulv[aulv.length]=i.toString();}for (i=0;i < 4;i++){aulv[aulv.length]='split'+i;}for (i=0;i < aulv.length;i++){aul+=_cRp('cr'+aulv[i],w['cr'+aulv[i]]);}var amts=[a0r,a1r,a2r,a3r];var txts=[a0d,a1d,a2d,a3d];for (i=0;i < 4;i++){n='cramount'+i;aul+=_cRp(n,amts[i] || w[n]);n='crtext'+i;aul+=_cRp(n,txts[i] || w[n]);}n=navigator;var qs="?siteid="+siteid+"&actn="+a+_cRs()+_cRp("referer",dD.URL)+aul+_cRp('ti',dD.title)+_cRp('l',n.userLanguage || n.language)+_cRp('sc',_cRh())+_cRp('j',_cRj())+_cRk()+_cRp('noland',CRNoLand)+(_cRY ? _cRp("cr_m",CRMemory) : "")+"&v=3938";return "http"+_cRaa+"://www.conversionruler.com/bin/tracker.php"+qs;}
function _cRac(x,t,f){if(document.attachEvent){x.attachEvent("on"+t,f);}else if(document.addEventListener){x.addEventListener(t,f,true);}}
function CRMemory_Set(i,v){if(i < 0 || i > 16){return false;}var om=CRMemory;var a=CRMemory.split('|');a[i]=v;CRMemory=a.join('|');if(CRMemory !==om){_cRY=true;if(_cRT && !_cRS){ _cRS=setTimeout(function(){_cRa();},500);}return true;}return false;}
function CRMemory_Get(i){var d=(arguments.length > 1) ? arguments[1] : '';if(i < 0 || i > 16){return d;}var a=CRMemory.split('|');if(typeof a[i]===_ud){return d;}if(a[i]===''){return d;}return a[i];}
function CRMemory_HiddenInput(i,n/*,uds */){return _cRm(n,arguments,2,CRMemory_Get(i));}
function CRMemory_Output(i/*,s0,s1,uds */){return _cRn(arguments,1,CRMemory_Get(i));}
function cr_track(a,a0r,a0d,a1r,a1d,a2r,a2d,a3r,a3d){var u,sid=__CR.site;if(!sid){__CR.site=sid=window.siteid;if(!sid){ return;}}a=_cRr(a,0);a0r=_cRy(a0r,"");a0d=_cRr(a0d,"");a1r=_cRy(a1r,"");a1d=_cRr(a1d,"");a2r=_cRy(a2r,"");a2d=_cRr(a2d,"");a3r=_cRy(a3r,"");a3d=_cRr(a3d,"");u=_cRu(sid,a,a0r,a0d,a1r,a1d,a2r,a2d,a3r,a3d);if(!u){if(_cRd){ alert('ConversionRuler: Already recorded this page');}return true;}_c2(u);_cRT=true;return true;}
function tlitrack(a,b,c,d,e){cr_track(a,b,c,d,e);}
function cr_submit(f,a,a0r,a0d,a1r,a1d,a2r,a2d,a3r,a3d){var w=f;if(typeof w.cr_submitted !==_ud){return true;}w.cr_submitted=true;_c0=null;window.cr_pixel_track=true;setTimeout(function(){cr_track(a,a0r,a0d,a1r,a1d,a2r,a2d,a3r,a3d);},5);if(w.target+"" !==""){return true;}setTimeout(function(){if(typeof w.submit !=="function"){ var e; try{ HTMLFormElement.prototype.submit.call(w); }catch (e){ w.submit(); }}else{ w.submit();}},100);return false;}
function cr_link(w,a,a0r,a0d,a1r,a1d,a2r,a2d,a3r,a3d){var t=w.target;var h=w.href;var f=null;setTimeout(function(){cr_track(a,a0r,a0d,a1r,a1d,a2r,a2d,a3r,a3d);},5);if(!t||t==="_self"){f=function(){document.location=h;};}else if(t==="_top"){f=function(){top.document.location=h;};}else if(t==="_parent"){f=function(){window.parent.document.location=h;};}if(f){setTimeout(f,100);return false;}return true;}
function cr_track_id(id,a,a0r,a0d,a1r,a1d,a2r,a2d,a3r,a3d){if(!document.getElementById){return;}var x=document.getElementById(id);if(!x){if(_cRd){ alert("No such advertisement found with id: "+id);}return;}var f=function (){cr_track(a,a0r,a0d,a1r,a1d,a2r,a2d,a3r,a3d);};_cRac(x,"mouseup",f);}
function _cR0a(w){var onload=null;if(typeof w.onload==="function"){onload=w.onload;}w.onload=function(){if(onload){ onload();}w.setInterval(function(){ var arg,type,tos=Object.prototype.toString;if(tos.call(w._crq) !=="[object Array]"){ return; } while (w._crq.length !==0){ w.cr_pixel_track=true; arg=w._crq.shift(); type=tos.call(arg);if(type==="[object Number]" || type==="[object String]"){  cr_track(arg); }else if(type==="[object Array]"){  cr_track.apply(undefined,arg); }else if(console && console.log){  console.log("Unknown type passed to _crq",type,arg); } }},100);};}if(typeof CRMemory_0 !==_ud){CRMemory_Set(0,CRMemory_0);}if(typeof CRMemory_1 !==_ud){CRMemory_Set(1,CRMemory_1);}if(typeof CRMemory_2 !==_ud){CRMemory_Set(2,CRMemory_2);}if(typeof CRMemory_3 !==_ud){CRMemory_Set(3,CRMemory_3);}_cR0a(window);